In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

2.3.1


In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [ ]:
df.head(4)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [5]:
print(len(df))

9704


In [6]:
unique_fueltypes = df['fuel_type']
unique_fueltypes.unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [7]:
uf2 = set(df['fuel_type'])
print(uf2)

{'Diesel', 'Gasoline'}


In [8]:
# columns in df 
df.columns

Index(['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain',
       'num_doors', 'fuel_efficiency_mpg'],
      dtype='object')

In [9]:
# Identify columns with any missing values
columns_with_missing_values = df.isnull().any()
print("Boolean Series of columns with missing values:\n", columns_with_missing_values)

# Get the names of columns with missing values
missing_column_names = df.columns[df.isnull().any()].tolist()
print("\nNames of columns with missing values:", missing_column_names)

Boolean Series of columns with missing values:
 engine_displacement    False
num_cylinders           True
horsepower              True
vehicle_weight         False
acceleration            True
model_year             False
origin                 False
fuel_type              False
drivetrain             False
num_doors               True
fuel_efficiency_mpg    False
dtype: bool

Names of columns with missing values: ['num_cylinders', 'horsepower', 'acceleration', 'num_doors']


In [10]:
# What's the maximum fuel efficiency of cars from Asia?
filtered_df_city = df[df['origin'] == 'Asia']
max_value = filtered_df_city['fuel_efficiency_mpg'].max()
max_value

np.float64(23.759122836520497)

In [11]:
#Q6 
# Find the median value of horsepower column in the dataset.
# Next, calculate the most frequent value of the same horsepower column.
# Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
# Now, calculate the median value of horsepower once again.

#df['horsepower'].tolist()

df['horsepower'].to_numpy()

array([159.,  97.,  78., ..., 138., 177., 140.], shape=(9704,))

In [12]:
df['horsepower'].median() #149.0

np.float64(149.0)

In [13]:
category_frequencies = df['horsepower'].value_counts()
print(category_frequencies.head(15))
# 152.0    142

horsepower
152.0    142
145.0    141
151.0    134
148.0    130
141.0    130
143.0    128
159.0    126
149.0    124
136.0    123
139.0    123
164.0    122
144.0    120
138.0    120
156.0    119
133.0    116
Name: count, dtype: int64


In [14]:
# fillna
# Replaces all NaN in column horsepower with 152.0
df_filled = df['horsepower'].fillna(152.0)
print(df_filled)

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64


In [15]:
df_filled.head(4)

0    159.0
1     97.0
2     78.0
3    152.0
Name: horsepower, dtype: float64

In [16]:
df_filled.median()

np.float64(152.0)

In [17]:
#Q7. Sum of weights

#Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
#Invert XTX.
#Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
#What's the sum of all the elements of the result?

In [18]:
# Select all the cars from Asia
# Select only columns vehicle_weight and model_year
# Select the first 7 values
filtered_df_city = df[df['origin'] == 'Asia']
filtered_df_city[['vehicle_weight', 'model_year']].head(7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [19]:
#Get the underlying NumPy array. Let's call it X.
import numpy as np
X = filtered_df_city[['vehicle_weight', 'model_year']].head(7).to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [20]:
#Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

# Transpose of X
XT = X.T
XT

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [21]:
XTX = X.dot(X.T)
XTX

array([[11431242.46085133, 11608190.92541486, 13770311.23387465,
        10111792.75336224, 11282536.19632532, 11780081.29349753,
        14281180.86123177],
       [11608190.92541486, 11790026.46575708, 14007802.20739725,
        10255171.44187306, 11455668.70489329, 11966096.78727446,
        14531088.48421337],
       [13770311.23387465, 14007802.20739725, 16863697.77478558,
        12031947.83608462, 13574023.463935  , 14232076.05656009,
        17530181.51805091],
       [10111792.75336224, 10255171.44187306, 12031947.83608462,
         9025088.58092514,  9989516.7638366 , 10397924.16669749,
        12456257.9230991 ],
       [11282536.19632532, 11455668.70489329, 13574023.463935  ,
         9989516.7638366 , 11136831.64128077, 11624252.15672766,
        14075069.26273247],
       [11780081.29349753, 11966096.78727446, 14232076.05656009,
        10397924.16669749, 11624252.15672766, 12145826.2645139 ,
        14766233.02574041],
       [14281180.86123177, 14531088.48421337, 175301

In [22]:
XTX = np.matmul(X.T,X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [23]:
#Invert XTX
inverse_xtx = np.linalg.inv(XTX)
inverse_xtx

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [24]:
#Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [25]:
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
result = np.matmul(inverse_xtx, X.T)
w = np.matmul(result, y)
w

array([0.01386421, 0.5049067 ])

In [26]:
#What's the sum of all the elements of the result?
w.sum()

np.float64(0.5187709081074016)