In [1]:
import numpy as np
import pandas as pd

In [2]:
u = np.array([2,4,5,6])
v = np.array([1,0,0,2])

In [3]:
v

array([1, 0, 0, 2])

In [4]:
u

array([2, 4, 5, 6])

In [7]:
u.shape[0]

4

In [8]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0] # match the size similarity

    
    n = u.shape[0]
    
    result = 0.0
    
    for each in range(n):
        result = result + u[each] * v[each]
    return result

In [9]:
vector_vector_multiplication(u, v)

np.float64(14.0)

In [10]:
u.dot(v)

np.int64(14)

In [9]:
## Matrix Vector Multiplication

In [11]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [12]:
U.shape

(3, 4)

In [13]:
v

array([1, 0, 0, 2])

In [14]:
U[0]

array([2, 4, 5, 6])

In [16]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == u.shape[0]

    num_rows = U.shape[0]
    # 3
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result    

In [17]:
U[2] * v # U[0] * v array([ 2,  0,  0, 12]) => 14
         # U[1] * v array([1, 0, 0, 4]) => 5
         # U[1] * v array([3, 0, 0, 2]) => 5

array([3, 0, 0, 2])

In [18]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [19]:
U.dot(v)

array([14,  5,  5])

In [20]:
## Matrix Matrix Multiplication

V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])

In [21]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [22]:
U.shape

(3, 4)

In [42]:
def matrix_matrix_multiplication(U, V):
    #print(U.shape[0]) #3
    #print(V.shape[1]) #3
    assert U.shape[0] ==  V.shape[1]

    row_count = U.shape[0]
    col_count = V.shape[1]

    result = np.zeros([row_count, col_count])

    # array([[0., 0., 0.],
    #   [0., 0., 0.],
    #   [0., 0., 0.]])

    # V[:,0], V[:,1], V[:,2]
    # (array([1., 0., 0., 2.]), array([1. , 0.5, 2. , 1. ]), array([2., 1., 1., 0.]))
    
    # Loop and call matrix_vector_multiplication (U, v)
    for i in range(col_count):
        #print(matrix_vector_multiplication(U, V[:,i]))
        result[:, i] = matrix_vector_multiplication(U, V[:,i])
    return result

In [43]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [44]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])