In [5]:
import numpy as np

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.full(5, 2.3)

array([2.3, 2.3, 2.3, 2.3, 2.3])

In [11]:
a = np.array([1,3,5,7,9,11])

In [12]:
a[2]

np.int64(5)

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [19]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
# "Multidimentional Array"

In [22]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
mu = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [29]:
mu[0, 1]

np.int64(2)

In [30]:
mu[0][1]

np.int64(2)

In [31]:
mu[1]

array([4, 5, 6])

In [36]:
mu [:, 1]

array([2, 5, 8])

In [37]:
# Random generated arrays

In [40]:
np.random.seed(2)
np.random.rand(5, 2) # 5 rows 2 columns

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [42]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2)) # 5 rows 2 columns

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [44]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [45]:
b = 10 + (a * 2)
b

array([10, 12, 14, 16, 18])

In [46]:
a + b

array([10, 13, 16, 19, 22])

In [47]:
# Comparison operations

In [48]:
a

array([0, 1, 2, 3, 4])

In [49]:
a >= 2

array([False, False,  True,  True,  True])

In [50]:
a.mean()

np.float64(2.0)

In [51]:
a.max()

np.int64(4)

In [52]:
a.std()

np.float64(1.4142135623730951)